version: '3.8'

services:
  producer:
    build: .
    command: ./run_producer.sh
    volumes:
      - ./example/:/src/app/config/
    env_file:
      - ./example/example.producer.env
  consumer:
    build: .
    command: ./run_consumer.sh
    volumes:
      - ./example/:/src/app/config/
    env_file:
      - ./example/example.consumer.env
